<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tibco.com/SecurityManagement/DataAccess/InsertAccessProfileByRole.wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="InsertAccessProfileByRole" targetNamespace="http://www.tibco.com/SecurityManagement/DataAccess/InsertAccessProfileByRole.wsdl" xmlns:xsd1="http://www.tibco.com/CLE/Schema/Private/SecurityConfiguration/AccessControl.xsd">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.tibco.com/SecurityManagement/DataAccess/InsertAccessProfileByRole.wsdl">
      <xsd:element name="InsertAccessProfileByRole">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="in" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="InsertAccessProfileByRoleResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Success" type="xsd:boolean"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    	<xsd:import
    		namespace="http://www.tibco.com/CLE/Schema/Private/SecurityConfiguration/AccessControl.xsd"
    		schemaLocation="../../../../Schemas/Private/SecurityConfiguration/AccessControl.xsd">
    	</xsd:import></xsd:schema></wsdl:types>
  <wsdl:message name="InsertAccessProfileByRoleRequest">
    <wsdl:part element="xsd1:RoleAccessProfile" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="InsertAccessProfileByRoleResponse">
    <wsdl:part element="tns:InsertAccessProfileByRoleResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="InsertAccessProfileByRole">
    <wsdl:operation name="InsertAccessProfileByRole">
      <wsdl:input message="tns:InsertAccessProfileByRoleRequest"/>
      <wsdl:output message="tns:InsertAccessProfileByRoleResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="InsertAccessProfileByRoleSOAP" type="tns:InsertAccessProfileByRole">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="InsertAccessProfileByRole">
      <soap:operation soapAction="http://www.tibco.com/SecurityManagement/DataAccess/InsertAccessProfileByRole.wsdl/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="InsertAccessProfileByRole">
    <wsdl:port binding="tns:InsertAccessProfileByRoleSOAP" name="InsertAccessProfileByRoleSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
