<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.example.org/schema/1456752520283" xmlns:extns1="http://www.tibco.com/schemas/CLE/SharedResources/SchemaDefinitions/Public/Pluggable/Workflow/Schema.xsd" xmlns:tns="http://www.example.org/wsdl/1456752520109" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HandleProcedureCompletion" targetNamespace="http://www.example.org/wsdl/1456752520109">
    <wsdl:import location="../../../Schemas/Public/Pluggable/Workflow/ProcedureCompletion.xsd" namespace="http://www.tibco.com/schemas/CLE/SharedResources/SchemaDefinitions/Public/Pluggable/Workflow/Schema.xsd"/>
    <wsdl:message name="operationRequest">
    <wsdl:part element="extns1:ProcedureCompletion" name="parameters"/>
  </wsdl:message>
    <wsdl:message name="operation1Request">
    <wsdl:part element="extns1:operation1Request" name="parameters"/>
  </wsdl:message>
    <wsdl:portType name="HandleProcedureCompletion">
    <wsdl:operation name="operation">
      <wsdl:input message="tns:operationRequest" name="operationInput"/>
      </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
