<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.tibco.com/CommonLE2/namespace/Public/Pluggable/GUI/Exception/ExceptionIDList" xmlns:part="http://www.tibco.com/CommonLE2/namespace/private/Common" xmlns:tns="http://www.tibco.com/ServiceDescriptors/ExceptionManagement/DataAccess/MSSQL/DeleteExceptions.wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DeleteExceptions" targetNamespace="http://www.tibco.com/ServiceDescriptors/ExceptionManagement/DataAccess/MSSQL/DeleteExceptions.wsdl" xmlns:xsd1="http://www.tibco.com/CommonLE2/Public/Common/Dummy">
  
  <wsdl:types>
  	<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  		<xsd:import
  			namespace="http://www.tibco.com/CommonLE2/namespace/private/Common"
  			schemaLocation="../../../../Schemas/Private/Common/LocalExceptions.xsd">
  		</xsd:import>
  		<xsd:import
  			namespace="http://www.tibco.com/CommonLE2/Public/Common/Dummy"
  			schemaLocation="../../../../Schemas/Public/Pluggable/GUI/Common/DummyReturnMessage.xsd">
  		</xsd:import>
  		<xsd:import
  			namespace="http://www.tibco.com/CommonLE2/namespace/Public/Pluggable/GUI/Exception/ExceptionIDList"
  			schemaLocation="../../../../Schemas/Public/Pluggable/GUI/ExceptionManagement/ExceptionIDList.xsd">
  		</xsd:import></xsd:schema></wsdl:types>
  <wsdl:message name="ExceptionIDList">
    <wsdl:part element="extns:ExceptionIDList" name="parameters" />
  </wsdl:message>
  <wsdl:message name="deleteResponse">
    <wsdl:part element="xsd1:Dummy" name="parameters" />
  </wsdl:message>
  <wsdl:message name="operationfault">
    <wsdl:part element="part:DBRecordNotFound" name="parameters" />
  </wsdl:message>
  <wsdl:portType name="DeleteExceptions">
    <wsdl:operation name="delete">
      <wsdl:input message="tns:ExceptionIDList" name="operationinput"/>
      <wsdl:output message="tns:deleteResponse" name="operationoutput"/>
      <wsdl:fault message="tns:operationfault" name="fault"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
