<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.tibco.com/CommonLE2/namespace/Private/Exception" xmlns:part="http://www.tibco.com/CommonLE2/Private/Exception" xmlns:tns="http://www.tibco.com/ServiceDescriptors/ExceptionManagement/DataAccess/MSSQL/RetrieveExceptionsBySchedule.wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RetrieveExceptionsBySchedule" targetNamespace="http://www.tibco.com/ServiceDescriptors/ExceptionManagement/DataAccess/MSSQL/RetrieveExceptionsBySchedule.wsdl">
  <wsdl:types>
  <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    		<xsd:import
    			namespace="http://www.tibco.com/CommonLE2/Private/Exception"
    			schemaLocation="../../../../Schemas/Private/Exception/ExceptionDetail.xsd">
    		</xsd:import>
    		<xsd:import
    			namespace="http://www.tibco.com/CommonLE2/namespace/Private/Exception"
    			schemaLocation="../../../../Schemas/Private/Exception/ExceptionParameters.xsd">
    		</xsd:import></xsd:schema>
  </wsdl:types>
  <wsdl:message name="ExceptionQuery">
    <wsdl:part element="extns:ExceptionQuery" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="retrieveResponse">
    <wsdl:part element="part:ExceptionDetails" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="RetrieveExceptionsBySchedule">
    <wsdl:operation name="retrieve">
      <wsdl:input message="tns:ExceptionQuery" name="operationinput"/>
      <wsdl:output message="tns:retrieveResponse" name="operationoutput"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
