<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.tibco.com/CommonLE2/namespace/Private/Exception" xmlns:tns="http://www.tibco.com/ServiceDescriptors/ExceptionManagement/DataAccess/MSSQL/UpdateExceptionSchedule.wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="UpdateExceptionSchedule" targetNamespace="http://www.tibco.com/ServiceDescriptors/ExceptionManagement/DataAccess/MSSQL/UpdateExceptionSchedule.wsdl">
  <wsdl:types>
  	<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  		<xsd:import
  			namespace="http://www.tibco.com/CommonLE2/namespace/Private/Exception"
  			schemaLocation="../../../../Schemas/Private/Exception/ExceptionParameters.xsd">
  		</xsd:import></xsd:schema></wsdl:types>
  <wsdl:message name="ExceptionSchedule">
    <wsdl:part element="extns:ExceptionSchedule" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="UpdateExceptionSchedule">
    <wsdl:operation name="update">
      <wsdl:input message="tns:ExceptionSchedule" name="updateinput"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
